import { createContext, useContext } from "react";

export type Lang = "ko" | "en";

export const LANGS: Lang[] = ["ko", "en"];

const STRINGS = {
  ko: {
    brandSub: "프로그램 {programs} · 문서 {documents} · 테이블 {tables}",
    searchPlaceholder: "계좌, TB_CUST, CustomerMapper …",
    noPrograms: "분석된 프로그램이 없습니다.",
    noResults: "검색 결과가 없습니다.",
    tablesLink: "테이블 목록 보기 →",
    sourceLink: "소스 브라우저 열기 →",
    loading: "불러오는 중…",

    homeLede:
      "운영 소스에서 자동 추출한 프로그램 명세서입니다. 배포 파이프라인에서 재생성되므로 항상 운영계와 같은 상태를 유지합니다.",
    statPrograms: "프로그램",
    statDocuments: "생성된 문서",
    statClasses: "클래스",
    statStatements: "SQL 문",
    statTables: "테이블",
    missingDocs: "산출물이 아직 생성되지 않은 프로그램 {count}건이 있습니다 —",
    missingDocsCmd: "를 실행하세요.",
    programsHeading: "프로그램",

    excelDownload: "Excel 내려받기",
    analyzedSources: "분석 대상 소스",
    openInBrowser: "소스 브라우저에서 열기",

    tablesTitle: "테이블",
    tablesLede: "테이블별 CRUD 와 이를 사용하는 프로그램입니다.",
    colTable: "테이블",
    colUsedBy: "사용 프로그램",
    crumbTable: "테이블",
    affectedPrograms: "영향받는 프로그램",
    sqlUsingTable: "이 테이블을 쓰는 SQL",

    sourceBrowser: "소스 브라우저",
    filterFiles: "파일 경로 검색…",
    findInFile: "파일 내 검색…",
    noFiles: "파일이 없습니다.",
    noMatch: "일치하는 파일이 없습니다.",
    pickFile: "왼쪽에서 파일을 선택하세요.",
    close: "닫기",
    copyPath: "경로 복사",
    copied: "복사됨",
    lines: "{n}줄",
    matches: "{n}건",
    prevMatch: "이전",
    nextMatch: "다음",
    parsedBadge: "분석됨",
    highlightOff: "파일이 커서 구문 강조를 껐습니다.",
  },
  en: {
    brandSub: "{programs} programs · {documents} docs · {tables} tables",
    searchPlaceholder: "account, TB_CUST, CustomerMapper …",
    noPrograms: "No programs have been analyzed.",
    noResults: "No results.",
    tablesLink: "Browse tables →",
    sourceLink: "Open source browser →",
    loading: "Loading…",

    homeLede:
      "Program specifications extracted automatically from the production source. They are regenerated by the deployment pipeline, so they always match what is running.",
    statPrograms: "Programs",
    statDocuments: "Documents",
    statClasses: "Classes",
    statStatements: "SQL statements",
    statTables: "Tables",
    missingDocs: "{count} program(s) have no generated document yet —",
    missingDocsCmd: "to create them.",
    programsHeading: "Programs",

    excelDownload: "Download Excel",
    analyzedSources: "Analyzed sources",
    openInBrowser: "Open in source browser",

    tablesTitle: "Tables",
    tablesLede: "CRUD per table and the programs that use it.",
    colTable: "Table",
    colUsedBy: "Programs",
    crumbTable: "TABLE",
    affectedPrograms: "Affected programs",
    sqlUsingTable: "SQL statements using this table",

    sourceBrowser: "Source browser",
    filterFiles: "Filter file paths…",
    findInFile: "Find in file…",
    noFiles: "No files.",
    noMatch: "No matching file.",
    pickFile: "Select a file on the left.",
    close: "Close",
    copyPath: "Copy path",
    copied: "Copied",
    lines: "{n} lines",
    matches: "{n} hits",
    prevMatch: "Prev",
    nextMatch: "Next",
    parsedBadge: "parsed",
    highlightOff: "Syntax highlighting is off for this large file.",
  },
} as const;

export type StringKey = keyof (typeof STRINGS)["ko"];

export function translate(
  lang: Lang,
  key: StringKey,
  vars?: Record<string, string | number>
): string {
  const text: string = STRINGS[lang][key] ?? STRINGS.ko[key] ?? key;
  if (!vars) return text;
  return text.replace(/\{(\w+)\}/g, (whole, name: string) =>
    name in vars ? String(vars[name]) : whole
  );
}

export interface LangValue {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: (key: StringKey, vars?: Record<string, string | number>) => string;
}

export const LangContext = createContext<LangValue>({
  lang: "ko",
  setLang: () => {},
  t: (key, vars) => translate("ko", key, vars),
});

export function useLang(): LangValue {
  return useContext(LangContext);
}

const STORAGE_KEY = "llmwiki.lang";

export function readStoredLang(): Lang | null {
  try {
    const v = localStorage.getItem(STORAGE_KEY);
    return v === "ko" || v === "en" ? v : null;
  } catch {
    return null;
  }
}

export function storeLang(lang: Lang): void {
  try {
    localStorage.setItem(STORAGE_KEY, lang);
  } catch {
    /* 프라이빗 모드 등에서 실패해도 무시 — 세션 안에서는 동작한다 */
  }
}
